### ISSUE TITLE
Meta-Ticket: Die verlorenen Wiki-Seiten wieder online bringen

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#143]
Das große Aufräumen in Essen hat auch Nachteile:
folgende doku fehlt und muss wiederhergestellt werden
- [x] links to addons/owncloud missing -> moved to communitywiki
- [x] links to addons/chilispot missing -> moved to rST
- [ ] links to sophomorix/ -> Ruediger will sort this out from the wikiarchiv -> github-devel-docs
- [x] links to addons/subnetting missing -> moved to rST, ticket #95 for the rest
- [x] download link from addons/monipi missing -> moved to lehrer.uni-karlsruhe.de temporarily
- [ ] links zur Virtualisierung -> communitywiki
- [ ] links zu techsheets -> temp. wikiarchiv -> github-devel-docs  oder communitywiki
- [ ] links zu "babo" -> temp. wikiarchiv -> github-devel-docs (base)
- [ ] handbuecher fehlen -> wikiarchiv
- [ ] verwaiste links im Wiki pflegen -> https://www.linuxmuster.net/wiki/playground:start&purge=true

* github-devel-docs: 
  * https://github.com/linuxmuster-docs/devel/wiki/Development-docs-overview
  * https://github.com/linuxmuster/sophomorix2/wiki (Sophomorix für v6.x)
  * https://github.com/linuxmuster/sophomorix4/wiki (Sophomorix für v7.x)
  * https://github.com/linuxmuster/linuxmuster-base/wiki (Linuxmuster base)
* communitywiki: https://www.linuxmuster.net/wiki/
* rST: http://docs.linuxmuster.net
* wikiarchiv: https://www.linuxmuster.net/wikiarchiv/
